name = "siren"
main = "build/worker/shim.mjs"
compatibility_date = "2026-07-01"
minify = true

[[kv_namespaces]]
binding = "SIREN"
id = "c9b1086e8b5d4be9a4802adbf3c48fb6"

[build]
command = "cargo install worker-build@0.1.0 --force && worker-build --release"

[env.dev]
build = { command = "cargo install worker-build && worker-build --dev" }

[vars]
UUID = "f282b878-8711-45a1-8c69-5564172123c1"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/FoolVPN-ID/Siren/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/FoolVPN-ID/Siren/refs/heads/master/web/sub.html"
